version: "3.7"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: speer
      POSTGRES_USER: vikhyat
      POSTGRES_PASSWORD: vikhyat

  adminer:
    image: adminer
    ports:
      - 9000:8080
